src/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup/', views.signup, name='signup'),
    url('login/', views.loginview, name='login'),
    url('logout/', views.logoutview, name='logout'),
]

src/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url('create/', views.create, name='create'),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name='upvote'),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name='downvote'),
    url(r'^user/(?P<fk>[0-9]+)', views.userposts, name='userposts'),
]

src/reddit_clone/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from posts import views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name='home'),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    votes_total = models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['password_conf']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error': 'User already exists'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords didn\'t match'})

    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'The user name and password didn\'t match'})
    else:
        return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

src/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from . models import Post
from django.contrib.auth.models import User
# Create your views here.

@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')

        else:
            return render(request, 'posts/create.html', {'error': 'ERROR: You have to have a title and url to create a post'})

    else:
        return render(request, 'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts': posts})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')


def userposts(request, fk):
    posts = Post.objects.filter(author__id=fk).order_by('-votes_total')
    author = User.objects.get(pk=fk)
    return render(request, 'posts/userposts.html', {'posts': posts, 'author': author})

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
  {% block content %}
    <div>
      <h1>Login</h1>
      {% if error %}
        {{ error }}
        <br />
        <br />
      {% endif%}
      <form action='{% url "accounts:login" %}' method='POST'>
        {% csrf_token %}
        {% if request.GET.next %}
          <input type='hidden' name='next' value={{ request.GET.next }} />
        {% endif %}
        Username:
        <br />
        <input type='text' name='username'/>
        <br />
        Password:
        <br />
        <input type='password' name='password' />
        <br />
        <br />
        <input class="btn btn-primary" type='submit' value='Log In' />
      </form>
    </div>
  {% endblock %}

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
  {% block content %}
    <div>
      <h1>Sign Up</h1>
      {% if error %}
        {{ error }}
        <br />
        <br />
      {% endif%}
      <form action='{% url "accounts:signup" %}' method='POST'>
        {% csrf_token %}
        Username:
        <br />
        <input type='text' name='username'/>
        <br />
        Password:
        <br />
        <input type='password' name='password' />
        <br />
        Confirm Password:
        <br />
        <input type='password' name='password_conf' />
        <br />
        <br />
        <input class="btn btn-primary" type='submit' value='Sign Up' />
      </form>
    </div>
  {% endblock %}

src/posts/templates/posts/create.html
{%extends 'base.html' %}
  {% block content%}
    <div>
      <h1>Post</h1>
      {% if error %}
        {{ error }}
        <br />
        <br />
      {% endif%}
      <form action='{% url "posts:create" %}' method='POST'>
        {% csrf_token %}
        Title:
        <br />
        <input type='text' name='title'/>
        <br />
        Link:
        <br />
        <input type='text' name='url' />
        <br />
        <br />
        <input class="btn btn-primary" type='submit' value='Post' />
      </form>
    </div>
{% endblock %}

src/posts/templates/posts/home.html
{% extends 'base.html' %}

  {% block content %}
    <h1 class="text-center">The home page of nowhere</h1>
    <a class="btn btn-primary btn-lg btn-block" href="{% url 'posts:create'%}">New Post</a>
    <br/>
    <br/>
    {% for post in posts.all %}
      <table>
        <tr>
          <td style="padding-right: 25px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-envelope"><strong>+</strong></span></a><br/> {{ post.votes_total }}<br/><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-envelope"><strong>-</strong></span></a></td>
          <td><a href="{{ post.url }}"> {{ post.title }}</a><br/>{{ post.pub_date_pretty }} by <a href='{% url "posts:userposts" post.author.id %}'>{{ post.author.username }}</a></td>
        </tr>
        <hr>

      </table>
      <form id='upvote{{ post.id }}' action='{% url "posts:upvote" post.id %}' method='POST'>
        {% csrf_token %}
        <input type='hidden'/>
      </form>

      <form id='downvote{{ post.id }}' action='{% url "posts:downvote" post.id %}' method='POST'>
        {% csrf_token %}
        <input type='hidden'/>
      </form>



    {% endfor %}
  {% endblock %}

src/posts/templates/posts/userposts.html
{% extends 'base.html' %}

  {% block content %}
    <h1>Posts by {{ author.username }}</h1>

    <br/>

    {% for post in posts.all %}
      <table>
        <tr>
          <td style="padding-right: 25px;"><a href="#" onClick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-envelope"><strong>+</strong></span></a><br/> {{ post.votes_total }}<br/><a href="#" onClick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-envelope"><strong>-</strong></span></a></td>
          <td><a href="{{ post.url }}"> {{ post.title }}</a><br/>{{ post.pub_date_pretty }} by <a href='{% url "posts:userposts" post.author.id %}'>{{ post.author.username }}</a></td>
        </tr>
        <hr>

      </table>
      <form id='upvote{{ post.id }}' action='{% url "posts:upvote" post.id %}' method='POST'>
        {% csrf_token %}
        <input type='hidden'/>
      </form>

      <form id='downvote{{ post.id }}' action='{% url "posts:downvote" post.id %}' method='POST'>
        {% csrf_token %}
        <input type='hidden'/>
      </form>



    {% endfor %}
  {% endblock %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Reddit Clone</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#" onClick="document.getElementById('logout').submit()">Logout</a>
                <form id='logout' method='post' action="{% url 'accounts:logout' %}">
                  {% csrf_token %}
                  <input type='hidden' >
                </form>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
              </li>
            {% endif %}
          </ul>
          <span class="navbar-text">
            Reddit Clone Using Django
          </span>
        </div>
      </nav>
    <div class='container'>
      {% block content %}
      {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>